# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZe58vvA1dfUfZfziioCfdgoo0z4Prvf
"""

scores = input().split()

total = 0
count = 0
counts = 0
maxn = int(scores[0])
minn = int(scores[0])

for s in scores:
    if int(s) > maxn:
        maxn = int(s)
    if int(s) < minn:
        minn = int(s)
  count = count + 1
  total = int(s) + total
  average = total/count
  if int(s) < 60:
    counts = counts + 1


for s in scores:
  count = count + 1
  total = int(s) + total
  average = total/count
  if int(s) < 60:
    counts = counts + 1

print(counts)
print(average)
print(f"max: {maxn}, minn: {minn}")