# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZe58vvA1dfUfZfziioCfdgoo0z4Prvf
"""

scores = input().split()

total = 0
count = 0

for s in scores:
  count = count + 1
  total = int(s) + total
  average = total/count

print(average)